import React, { Component } from 'react';

import { Input, Row, Col, Descriptions, Card, Select, Table, Space, Collapse, Button, Divider } from 'antd';

const { Column } = Table;
const { Option } = Select;

const gridStyle = {
    width: '25%',
    // textAlign: 'center',
};

const gridStyle2 = {
    width: '16%',
    // textAlign: 'center',
};

const gridStyle3 = {
    width: '32%',
    // textAlign: 'center',
};

class CaseTable extends Component {
    constructor() {
        super()

        this.state = {
            ID: '',
            columns: [
                {
                    "caseId": "2022040100",
                    "name": "张建国",
                    "gender": "男",
                    "firstAge": "25",
                    "curePeriod": "30",
                    "isRegular": "是",
                    "isTeacher": "是",
                }
            ]
        }
    }
    componentDidMount() {
        fetch('http://127.0.0.1:5000/get_list/',
            {
                method: 'GET'
            })
            .then(response => response.json())
            .then(response => {
                console.log(response);
                console.log("data is ", response)
                response = response.list
                // for (let i = 0; i < response.length; i++){
                //     response[i]['linkID'] = response[i]['patientID']
                // }
                this.setState({
                    columns: response
                })
            });
        console.log("state is", this.state)
    }

    changeDisplay = (text, record) => {
        console.log("text is ", text)
        console.log("record is ", record)
        this.props.changeDisplay()
        this.props.setPatientID(text.patientID)
    }

    queryInfo = () => {
        this.props.changeDisplay()
        this.props.setPatientID(this.state.ID)
    }

    handleInput = (event) => {
        this.setState({
            ID: event.target.value
        });
    }
    render() {
        // console.log("Table", this.props.displayState)
        let ifDisplay = ''
        if (this.props.displayState == 'table') {
        }
        else {
            ifDisplay = 'none'
        }
        console.log(this.state.columns)
        return (
            <div style={{ display: ifDisplay }}>
                <h1>病历系统</h1>
                <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
                    <Row justify="space-between">
                        <Col span={17} >
                            <Input size="large" autoFocus={true} onChange={this.handleInput} placeholder="请输入患者病历号"/>
                        </Col>
                        <Col span={6} >
                            <Button size="large" type="primary" block
                                className="btn btn-primary btn-lg"
                                onClick={this.queryInfo}
                            >查询</Button>
                        </Col>
                        {/* <Col span={2}></Col> */}
                    </Row>
                    <Table dataSource={this.state.columns} pagination={{ pageSize: 8 }}>
                        <Column title='序号' dataIndex='backupNo' render={(text, recorder, index) => <span>{index + 1}</span>} />
                        {/* <Column title='病历号' dataIndex='patientID' render={text => <text style={{ color: "#40a9ff" }}>{text}</text>} /> */}
                        <Column title='病历号' dataIndex='patientID' />
                        <Column title='姓名' dataIndex='name' />
                        <Column title='性别' dataIndex='gender' />
                        <Column title='首诊年龄（岁）' dataIndex='firstVisitAge' />
                        <Column title='治疗时间（天）' dataIndex='treatTime' />
                        <Column title='是否规律' dataIndex='isRegular' />
                        <Column title='是否老师' dataIndex='isTeacher' />
                        <Column title='详情' render={(text, record) => <Button size="default" type="primary" onClick={() => this.changeDisplay(text, record)}>查看详情</Button>} />
                    </Table>
                </Space>

            </div>
        )
    }
}

class CaseDetail extends Component {
    constructor(props) {
        super(props)
        this.state = {
            focus: 47,
        }
    }

    handleChangeFocus = (event) => {
        console.log(event)
        this.setState({
            focus: event
        });
    }
    render() {
        // console.log("Detail", this.props.displayState)
        let ifDisplay = ''
        if (this.props.displayState == 'table') {
            ifDisplay = 'none';
        }
        else {
        }
        // console.log(ifDisplay)

        const validIndex = [47, 46, 45, 44, 43, 42, 41, 37, 36, 35, 34, 33, 32, 31, 27, 26, 25, 24, 23, 22, 21, 17, 16, 15, 14, 13, 12, 11];
        const validIndexItems = validIndex.map((number) =>
            <Option key={number} value={number}>{number}</Option>
        );
        const zhibiao = [
            "BI_B",
            "BI_DB",
            "BI_DL",
            "BI_L",
            "BI_MB",
            "BI_ML",

            "PD_B",
            "PD_DB",
            "PD_DL",
            "PD_L",
            "PD_MB",
            "PD_ML",

            "FI_B",
            "FI_L",
            "动度",

            "溢脓_B",
            "溢脓_DB",
            "溢脓_DL",
            "溢脓_L",
            "溢脓_MB",
            "溢脓_ML",
            "龈退缩_B",
            "龈退缩_DB",
            "龈退缩_DL",
            "龈退缩_L",
            "龈退缩_MB",
            "龈退缩_ML"];
        const zhibiaoName = [
            "@BI@B      \t=\t",
            "@BI@DB     \t=\t",
            "@BI@DL     \t=\t",
            "@BI@L      \t=\t",
            "@BI@MB     \t=\t",
            "@BI@ML     \t=\t",
            "@PD@B      \t=\t",
            "@PD@DB     \t=\t",
            "@PD@DL     \t=\t",
            "@PD@L      \t=\t",
            "@PD@MB     \t=\t",
            "@PD@ML     \t=\t",
            "@FI@B      \t=\t",
            "@FI@L      \t=\t",
            "@动度      \t=\t",
            "@溢脓@B    \t=\t",
            "@溢脓@DB   \t=\t",
            "@溢脓@DL   \t=\t",
            "@溢脓@L    \t=\t",
            "@溢脓@MB   \t=\t",
            "@溢脓@ML   \t=\t",
            "@龈退缩@B  \t=\t",
            "@龈退缩@DB \t=\t",
            "@龈退缩@DL \t=\t",
            "@龈退缩@L  \t=\t",
            "@龈退缩@MB \t=\t",
            "@龈退缩@ML \t=\t"
        ];
        const teethGrid = zhibiao.map((myindex, index) => {
            if (index == 12 || index == 13 || index == 14) {
                return <Card.Grid style={gridStyle3} key={myindex}>{zhibiaoName[index]}<strong>{this.props.teethArray[this.state.focus][myindex]}</strong></Card.Grid>
            }
            else {
                return <Card.Grid style={gridStyle2} key={myindex}>{zhibiaoName[index]}<strong>{this.props.teethArray[this.state.focus][myindex]}</strong></Card.Grid>
            }
        }

        );
        const focus = this.state.focus;

        return (
            <div style={{ display: ifDisplay }}>
                <Space direction="vertical" size="middle" style={{ display: 'flex' }}>
                    <h1 className='title'>患者详情</h1>

                    {/* <Descriptions title="基本信息" layout="vertical" bordered='true' column={{ xxl: 4, xl: 4, lg: 4, md: 3, sm: 2, xs: 1 }}>
                        <Descriptions.Item label="病历号"><text>{this.props.patientID}</text></Descriptions.Item>
                        <Descriptions.Item label="姓名"><text>{this.props.patientInfo.name}</text></Descriptions.Item>
                        <Descriptions.Item label="首诊年龄（岁）"><text>{this.props.patientInfo.firstVisitAge}</text></Descriptions.Item>
                        <Descriptions.Item label="性别"><text>{this.props.patientInfo.gender}</text></Descriptions.Item>
                        <Descriptions.Item label="治疗时间（天）" ><text>{this.props.patientInfo.treatTime}天</text></Descriptions.Item>
                        
                        <Descriptions.Item label="是否规律治疗" ><text>{this.props.patientInfo.isRegular}</text></Descriptions.Item>
                        <Descriptions.Item label="是否老师治疗" ><text>{this.props.patientInfo.isTeacher}</text></Descriptions.Item>
                    </Descriptions> */}

                    <Card title="基本信息">
                        <Card.Grid style={gridStyle}><text>姓名：{this.props.patientInfo.name}</text></Card.Grid>
                        <Card.Grid style={gridStyle}><text>性别：{this.props.patientInfo.gender}</text></Card.Grid>
                        <Card.Grid style={gridStyle}><text>首诊年龄：{this.props.patientInfo.firstVisitAge}</text></Card.Grid>
                        <Card.Grid style={gridStyle}><text>治疗时间：{this.props.patientInfo.treatTime}天</text></Card.Grid>
                        <Card.Grid style={gridStyle}><text>病历号：{this.props.patientID}</text></Card.Grid>
                        {/* <Card.Grid style={gridStyle}><text>{this.props.patientInfo.isRegular=="是"?"":"未"}规律治疗</text></Card.Grid> */}
                        <Card.Grid style={gridStyle}><text>是否规律治疗：{this.props.patientInfo.isRegular}</text></Card.Grid>
                        <Card.Grid style={gridStyle}><text>是否老师治疗：{this.props.patientInfo.isTeacher}</text></Card.Grid>
                    </Card>

                    {/* <Divider /> */}
                    {/* <text>请选择牙齿编号</text> */}
                    <Select defaultValue="47" style={{ width: 520 }} onChange={this.handleChangeFocus}>
                        {validIndexItems}
                    </Select>
                    <Card title="牙齿信息（请在上方选择牙齿编号）">
                        {teethGrid}
                    </Card>
                    <Button block size="large" type="primary" onClick={this.props.changeDisplay}>
                        返回
                    </Button>
                </Space>
            </div>
        )
    }
}

class CaseHistory extends Component {
    constructor(props) {
        super(props);
        this.state = {
            displayState: "table",
            patientID: '',
            patientInfo: {},
            teethArray: [
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "0",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "1",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "2",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "3",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "4",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "5",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "6",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "7",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "8",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "9",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "10",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "3",
                    "PD_DB": "2",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "4",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "11",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "12",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "13",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "14",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "15",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "16",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "17",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "18",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "19",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "20",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "21",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "22",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "23",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "24",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "25",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "26",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "27",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "28",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "29",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "30",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "31",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "32",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "33",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "34",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "35",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "36",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "37",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "38",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "39",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "40",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "41",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "42",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "43",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "44",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "45",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "",
                    "PD_DB": "",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "46",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                },
                {
                    "BI_B": "",
                    "BI_DB": "",
                    "BI_DL": "",
                    "BI_L": "",
                    "BI_MB": "",
                    "BI_ML": "",
                    "FI_B": "",
                    "FI_L": "",
                    "PD_B": "2",
                    "PD_DB": "2",
                    "PD_DL": "",
                    "PD_L": "",
                    "PD_MB": "",
                    "PD_ML": "",
                    "finished": false,
                    "teethID": "47",
                    "动度": "",
                    "溢脓_B": "",
                    "溢脓_DB": "",
                    "溢脓_DL": "",
                    "溢脓_L": "",
                    "溢脓_MB": "",
                    "溢脓_ML": "",
                    "龈退缩_B": "",
                    "龈退缩_DB": "",
                    "龈退缩_DL": "",
                    "龈退缩_L": "",
                    "龈退缩_MB": "",
                    "龈退缩_ML": ""
                }
            ]
        };
    }

    changeDisplay = () => {
        var st = this.state.displayState;
        let newState = '';
        if (st == "table") newState = "detail";
        else newState = "table";
        console.log(st, newState);
        this.setState({
            displayState: newState
        });
    }

    setPatientID = (id) => {
        fetch('http://127.0.0.1:5000/get_patient/',
            {
                headers: {
                    'Accept': 'application/text',
                    'Content-Type': 'application/json'
                },
                method: 'POST',
                body: id
            })
            .then(response => response.json())
            .then(response => {
                console.log("-----------------详细信息---------------------")
                console.log("detail response", response);
                this.setState({
                    patientID: id,
                    patientInfo: response.result.patientInfo,
                    teethArray: response.result.teethArray
                })
            });
    }
    render() {
        return (
            <div>
                <CaseTable displayState={this.state.displayState} changeDisplay={this.changeDisplay} patientID={this.state.patientID} setPatientID={this.setPatientID} />
                <CaseDetail displayState={this.state.displayState} changeDisplay={this.changeDisplay} patientID={this.state.patientID} setPatientID={this.setPatientID} patientInfo={this.state.patientInfo} teethArray={this.state.teethArray} />
            </div>
        )
    }
}


export default CaseHistory